Update-layout
classroomtv/DataPanel pull request #17
Opened 2023-01-04 17:55 UTC by matipina

- Implemented function to reuse code when creating the plots
- Added missing metrics for texts, scroms and classes counts
- Included all plots inside expander widgets
- Implemented checkbox to select which plots to show

2023-01-05 04:41 UTC, Wamedina requested changes
Hay unos cambios que revisar antes de mergear!

2023-01-05 04:41 UTC, Wamedina commented on pages/2_Analysis_by_Institution.py
> +            show_data_by_date(key, dataframes_dict[key], df_institutions_selection)
Por el método que implementaste se muestran todas las columnas del dataframe, con lo que se muestran índices y columnas que no deberían, sería ideal agregar como key del método las columnas que queremos mostrar!

2023-01-05 04:41 UTC, Wamedina commented on downloadCsvFromQueries.ipynb
>   ],
A qué corresponden estos cambios?

2023-01-05 04:41 UTC, Wamedina commented on utils/auxiliar_functions.py
> +def show_data_by_date(title, data, df_institutions_selection):
Hice unos pequeños cambios a las consultas que ejecutamos para extraer los csv para homologar todos los nombres en inglés, subí estos cambios a tu branch, dependiendo de como vaya en la semana implementaré los cambios que te comenté arriba ajaj

2023-01-09 18:15 UTC, matipina commented on pages/2_Analysis_by_Institution.py
> +            show_data_by_date(key, dataframes_dict[key], df_institutions_selection)
👍

2023-01-09 18:36 UTC, Wamedina commented on utils/auxiliar_functions.py
> +            #st.dataframe(data_df[["title","create_time", "view_count", "author_id", "signed_users","user_finished_courses", "user_failed_courses"]].sort_values(by="create_time"))
Eliminar liínas comentadas

2023-01-09 18:45 UTC, Wamedina approved these changes
Nice! Good job!

2023-01-09 18:47 UTC, matipina commented
Updated the layout to include all needed data

2023-01-09 18:48 UTC, merged